### test signup user with unique email
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "john@hotmail.com",
    "password": "01245"
}


###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "john@hotmail.com",
    "password": "01245"
}

###
POST http://localhost:3000/auth/signout

###
GET http://localhost:3000/auth

###
GET http://localhost:3000/auth/1

###
GET http://localhost:3000/auth/whoami

###
PATCH http://localhost:3000/auth/1


###
DELETE http://localhost:3000/auth/1

###
GET http://localhost:3000/auth/whoami