### test signup user with unique email
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "john@hotmail.com",
    "password": "01245"
}


###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "john@hotmail.com",
    "password": "01245"
}

###
POST http://localhost:3000/auth/signout

###
GET http://localhost:3000/auth

###
GET http://localhost:3000/auth/1

###
GET http://localhost:3000/auth/whoami

###
PATCH http://localhost:3000/auth/1


###
DELETE http://localhost:3000/auth/1

###
GET http://localhost:3000/auth/whoami

###
POST http://localhost:3000/vehicules/create
Content-Type: application/json

{
    "type": 0,
    "model": "ford",
    "carryingSpace": 14,
    "costPerKm": 5,
    "maxWeight": 500
}


###
POST http://localhost:3000/vehicules/create
Content-Type: application/json

{
    "type": 1,
    "model": "chevrolet",
    "carryingSpace": 18,
    "costPerKm": 8,
    "maxItemHeight": 8 
}

###
Get http://localhost:3000/vehicules/all


###
Get http://localhost:3000/vehicules/trucks

###
Get http://localhost:3000/vehicules/vans


###
PATCH http://localhost:3000/vehicules/1
Content-Type: application/json

{
  "model": "gmc"
}

###
GET http://localhost:3000/vehicules/1

###
DELETE http://localhost:3000/vehicules/1