### Create User | Sign Up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "type": "Client",
    "email": "client1@outlook.com",
    "password": "pswrd"
}

### Sign In User
GET http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "admin1@outlook.com",
    "password": "pswrd"
}

### Sign Out User
Post http://localhost:3000/auth/signout

### Who Am I 
GET http://localhost:3000/auth/whoami

### Update User
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
    "email": "khaled@outlook.com",
    "password": "yf8/$?/9na?&wsf!/$7()*wq9cntqsqw",
    "firstName": "Khaled",
    "lastName": "Abou Hechmeh"
}

### Get All Users
GET http://localhost:3000/auth

### Get User By Id
GET http://localhost:3000/auth/1

### Delete User By Id
DELETE http://localhost:3000/auth/2

################# Vehicles

### Create Vehicle
POST http://localhost:3000/vehicles/create
Content-Type: application/json

{
    "type": "Van",
    "model": "random",
    "carryingSpace": 50,
    "costPerKm": 1.2,
    "maxItemHeight": 2
}

### Get All Vehicles
GET http://localhost:3000/vehicles/all

### Get All Trucks
GET http://localhost:3000/vehicles/trucks

### Get All Vans
GET http://localhost:3000/vehicles/vans

################# Locations

### Create Location
POST http://localhost:3000/locations/create
Content-Type: application/json

{
    "depotName": "rand123",
    "lon": 40,
    "lat": 50
}

### Get All Locations
GET http://localhost:3000/locations/all

################# Carts

### Get All Carts
GET http://localhost:3000/carts/all

### Pay with Credit Card
POST http://localhost:3000/carts/pay?type=creditcard&amount=100

### Pay with Paypal
POST http://localhost:3000/carts/pay?type=paypal&amount=100