### Create admin | Sign Up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "userType": "Admin",
    "email": "admin1@outlook.com",
    "password": "pswrd"
}


### Create user | Sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "userType": "Client",
    "email": "client1@outlook.com",
    "password": "pswrd"
}

### Sign In User
GET http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "client1@outlook.com",
    "password": "pswrd"
}

### Sign Out User
Post http://localhost:3000/auth/signout

### Who Am I 
GET http://localhost:3000/auth/whoami

### Update User
PATCH http://localhost:3000/users/3
Content-Type: application/json

{
    "email": "khaled@outlook.com",
    "password": "yf8/$?/9na?&wsf!/$7()*wq9cntqsqw",
    "firstName": "Khaled",
    "lastName": "Abou Hechmeh"
}

### Get All Users
GET http://localhost:3000/users

### Get User By Id
GET http://localhost:3000/users/1

### Delete User By Id
DELETE http://localhost:3000/users/1