### Sign In as Client
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "userType": "Client",
    "email": "client1@outlook.com",
    "password": "pswrd"
}

### View Cart/api
GET http://localhost:3000/api/carts/currentCart

### Add Vehicle to Cart
PATCH http://localhost:3000/api/reservations/addVehicle
Content-Type: application/json

{
    "vehicleId": 1,
    "distance": 40
}

### Remove Order Item from Cart
PATCH http://localhost:3000/api/reservations/removeOrderItem/3

### Pay for Cart
POST http://localhost:3000/api/carts/pay?method=paypal&amount=80
Content-Type: application/json

{
    "method": "PayPal",
    "amount": 62.8
}
