### Sign In as Admin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "admin1@outlook.com",
    "password": "pswrd"
}

### Create Vehicle
POST http://localhost:3000/vehicles/create
Content-Type: application/json

{
    "licencePlate": "11A 123",
    "vehicleSubtype": "Large Box"
}

### Get All Vehicles
GET http://localhost:3000/vehicles/all

### Get All Trucks
GET http://localhost:3000/vehicles/trucks

### Get All Trailers
GET http://localhost:3000/vehicles/trailers

### get vehicle by id
GET http://localhost:3000/vehicles/12


### chec if road safe
GET http://localhost:3000/vehicles/12/roadSafe

### Update
PATCH http://localhost:3000/vehicles/12
Content-Type: application/json

{
  "kilometrage": 250000,
  "isReserved": true,
  "kilometrageSecuritaire": false
}

### delete vehicle by id
DELETE http://localhost:3000/vehicles/12
