################# Locations

### Create Location
POST http://localhost:3000/api/locations/create
Content-Type: application/json

{
  "depotName": "Montreal Depot",
  "address": "1000 Rue de la Gauchetière, Montreal, QC",
  "phoneNumber": "514-555-0100"
}

### Get All Locations
GET http://localhost:3000/api/locations/all


### Add location to vehicle
POST http://localhost:3000/api/locations/addVehicle
Content-Type: application/json

{
    "vehicleId" : 2,
    "locationId": 1
}

### Remove location to vehicle
PATCH http://localhost:3000/api/locations/removeVehicle
Content-Type: application/json

{
    "locationId": 1,
    "vehicleId" : 2
}

### Delete location
DELETE http://localhost:3000/api/locations/1