### Create admin | Sign Up
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "name": "Khaled",
    "surname": "Abou Hechmeh",
    "userType": "Admin",
    "adminType": "Super Admin", 
    "email": "khaled@uowl.com",
    "password": "pswrd"
}

### Sign In User
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "userType": "Admin",
    "email": "khaled@uowl.com",
    "password": "pswrd"
}

### Sign Out User
Post http://localhost:3000/api/auth/signout

### Who Am I 
GET http://localhost:3000/api/auth/whoami

### Update User
PATCH http://localhost:3000/api/users/1
Content-Type: application/json

{
    "email": "admin1@outlook.com",
    "password": "pswrd",
    "name": "Khaled",
    "surname": "Abou Hechmeh"
}

### Change a user's password
PATCH http://localhost:3000/api/users/2/changePassword/password123

### Get All Users
GET http://localhost:3000/api/users

### Get User By Id
GET http://localhost:3000/api/users/2

### Delete User By Id
DELETE http://localhost:3000/api/users/1