### ─────────────────────────────────────────
###  VEHICLES  (/api/vehicles)
### ─────────────────────────────────────────

### Create Vehicle  [AdminGuard]
POST http://localhost:3000/api/vehicles/create
Content-Type: application/json

{
    "licencePlate": "11A 123",
    "vehicleSubtype": "Large Box"
}

### Get All Vehicles
GET http://localhost:3000/api/vehicles/all

### Get All Trucks
GET http://localhost:3000/api/vehicles/trucks

### Get All Trailers
GET http://localhost:3000/api/vehicles/trailers

### Check If Vehicle Is Road Safe  [AdminGuard]
GET http://localhost:3000/api/vehicles/12/roadSafe

### Update Vehicle  [AdminGuard]
PATCH http://localhost:3000/api/vehicles/12
Content-Type: application/json

{
    "kilometrage": 250000,
    "isReserved": true,
    "isSafe": false
}

### Delete Vehicle By Id  [AdminGuard]
DELETE http://localhost:3000/api/vehicles/12
